config/routes.rb
Rails.application.routes.draw do
  get 'hotel/index'
  get 'travel/index'
  get 'home/index'
  get 'flight/index'

  devise_for :users
  root to: "home#index"
  
  get '/search' => 'travel#search'
  get '/searchhotel' => 'hotel#searchhotel'
  get '/airline_info' => 'flight#airline_info'
  get '/flight_inspiration' => 'flight#flight_inspiration'
  get '/flight_lowfare' => 'flight#flight_lowfare'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/hotel_controller.rb
require 'amadeus'

class HotelController < ApplicationController
  def index
  end
  def searchhotel
    hotel = find_hotel_offers(params[:citycode], params[:checkInDate], params[:checkOutDate], params[:adults])
  
    unless hotel
      flash[:alert] = 'Could not get Hotel Info'
      return render action: :index
    end
    @hotelList = hotel
  end

  def find_hotel_offers(citycode, checkInDate, checkOutDate, adults)
    amadeus = hotel_conexion()
    puts citycode
    response = amadeus.shopping.hotel_offers.get(cityCode: (URI.encode(citycode)))
    response.data
  end

  def hotel_conexion()

    amadeus = Amadeus::Client.new({
      client_id: 'GfCm2MQJMp5cWOuEF3Gs1dong3lL7wrK',
      client_secret: '1a4VItWsGjz0dVIp'
    })

  end
end

app/helpers/hotel_helper.rb
module HotelHelper
    class City < ActiveRecord::Base
        enum city: { 
            Aalborg_Dinamarca_ALL: "AAL", 
            Aalesund_Noruega_AES: "AES", 
            Acapulco_México_ACA: "ACA", 
            Aguascalientes_México_AGU:"AGU",
            Aguadilla_Puerto_Rico_BQN: "BQN",
            Bagotville_PQ_Canadá_YBG: "YBG",
            Bangda_China_BPX: "BPX",
            Bangkok_Tailandia_BKK: "BKK",
            Bangui_República_Centroafricana_BGF: "BGF",
            Barcelona_España_BCN: "BCN",
            Bari_Italia_BRI: "BRI",
            Barisal_Bangladesh_BZL: "BZL",
            Barranquilla_Colombia_BAQ: "BAQ",
            San_Carlos_de_Bariloche_Argentina_BRC: "BRC",
            San_Diego_CA_EE_UU_SAN: "SAN",
            San_Francisco_CA_EE_UU_SFO: "SFO",
            San_José_Costa_Rica_SJO: "SJO",
            San_José_CA_EE_UU_SJC: "SJC",
            San_Juan_Puerto_Rico_SJU: "SJU",
            San_Luis_Potosi_México_SLP: "SLP",
            San_Salvador_El_Salvador_SAL: "SAL",
            Santa_Cruz_España_SPC: "SPC",
            Santa_Cruz_de_Tenerife_Canary_Islands_TFN: "TFN",
            Santa_Fe_Nuevo_México_EE_UU_SAF: "SAF",
            Santa_Maria_CA_EE_UU_SMX: "SMX",
            Santa_Maria_Sal_Island_Cabo_Verde_SID: "SID",
            Santa_Rosa_Argentina_RSA: "RSA",
            Santa_Rosa_CA_EE_UU_STS: "STS",
            Santander_España_SDR: "SDR",
            Santiago_Chile_SCL: "SCL",
            Santiago_República_Dominicana_STI: "STI",
            Santo_Domingo_República_Dominicana_SDQ: "SDQ",
            Madrid_España_MAD: "MAD",
            New_York_EE_UU_NYC: "NYC",
        }
       
    end
    class Guest < ActiveRecord::Base
        enum guest: { 
            one: "1", 
            two: "2", 
            three: "3", 
            four: "4", 
            five: "5", 
            six: "6", 
            seven: "7", 
            eight: "8", 
            nine: "9" 
        }
    end
end

app/views/hotel/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 mt-5">
      <div class="mx-auto mt-5" style="width: 400px">
        <%= form_with(url: searchhotel_path, method: 'get', local: true) do %>
          <div class="form-group">
            <%= label_tag :citycode, 'Search for a airline information by code '%>
            <%= text_field_tag :citycode, nil, placeholder: 'Eg. AA', class: 'form-control' %>
          </div>
          <%= button_tag 'Search', class: 'btn btn-success btn-block' %>
        <% end %>
      </div>
      <div class="col-lg-12 mt-5">
      <% if flash[:alert] %>
        <div class="alert alert-warning"><%= flash[:alert] %></div>
      <% end %>

      <div class="mx-auto mt-5" style="width: 400px">
    </div>
  </div>
</div>

app/views/hotel/searchhotel.html.erb
<header>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'bootstrap', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- Theme style  -->
    <%= stylesheet_link_tag 'style', media: 'all', 'data-turbolinks-track': 'reload' %> 
</header>
<body>
<%= render 'layouts/navigation' %>
		
<div class="colorlib-loader"></div>

<div id="page">
    <div class="colorlib-wrap">
        <div class="container">
            <div class="row">
                <div class="col-md-14">
                    <div class="row">
                        <div class="wrap-division">
                            <% @hotelList.each do |hotel| %>
                                <div class="col-md-4 col-sm-4 animate-box">
                                    <div class="hotel-entry">
                                        <%= image_tag Dir.new(Rails.root.to_s + "/app/assets/images").to_a.select{|f|  f.downcase.match(/\.jpg|\.jpeg|\.png/) }.sample, class:"hotel-img", style:"width: 400px" %>
                                            <p class="price">
                                            <span>
                                               $ <%= hotel['offers'][0]['price']['total']%>
                                            </span>
                                            <small> /night</small></p>
                                        <div class="desc">
                                            <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i></span> 545 Reviews</p>
                                            <h3><%= hotel['hotel']['name']%> | <%= hotel['hotel']['address']['cityName']%> </h3>
                                            <span class="place">
                                                <%= hotel['hotel']['chainCode']%>
                                            </span>
                                            <span>
                                                <i class="icon-phone"></i>
                                                <%= hotel['hotel']['contact']['phone']%>
                                            </span>
                                            <h6>Address:</h6>
                                            <p><%= hotel['hotel']['address']['lines'].to_s.gsub(/^\[+|\]+$/, '')%> | <%= hotel['hotel']['cityCode']%> | <%= hotel['hotel']['address']['countryCode']%></p>
                                           
                                        </div>
                                    </div>
                                </div>
                            <%end%>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>

<div class="gototop js-top">
    <a href="#" class="js-gotop"><i class="icon-arrow-up2"></i></a>
</div>

</body>