config/routes.rb
Rails.application.routes.draw do
  get 'hotel/index'
  get 'travel/index'
  get 'home/index'
  get 'flight/index'

  devise_for :users
  root to: "home#index"
  
  get '/search' => 'travel#search'
  get '/searchhotel' => 'hotel#searchhotel'
  get '/airline_info' => 'flight#airline_info'
  get '/flight_inspiration' => 'flight#flight_inspiration'
  get '/flight_lowfare' => 'flight#flight_lowfare'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper

    class LowFareOrigin < ActiveRecord::Base
        enum origin: { 
            Aalborg_Dinamarca_ALL: "AAL", 
            Aalesund_Noruega_AES: "AES", 
            Acapulco_México_ACA: "ACA", 
            Aguascalientes_México_AGU:"AGU",
            Aguadilla_Puerto_Rico_BQN: "BQN",
            Bagotville_PQ_Canadá_YBG: "YBG",
            Bangda_China_BPX: "BPX",
            Bangkok_Tailandia_BKK: "BKK",
            Bangui_República_Centroafricana_BGF: "BGF",
            Barcelona_España_BCN: "BCN",
            Bari_Italia_BRI: "BRI",
            Barisal_Bangladesh_BZL: "BZL",
            Barranquilla_Colombia_BAQ: "BAQ",
            San_Carlos_de_Bariloche_Argentina_BRC: "BRC",
            San_Diego_CA_EE_UU_SAN: "SAN",
            San_Francisco_CA_EE_UU_SFO: "SFO",
            San_José_Costa_Rica_SJO: "SJO",
            San_José_CA_EE_UU_SJC: "SJC",
            San_Juan_Puerto_Rico_SJU: "SJU",
            San_Luis_Potosi_México_SLP: "SLP",
            San_Salvador_El_Salvador_SAL: "SAL",
            Santa_Cruz_España_SPC: "SPC",
            Santa_Cruz_de_Tenerife_Canary_Islands_TFN: "TFN",
            Santa_Fe_Nuevo_México_EE_UU_SAF: "SAF",
            Santa_Maria_CA_EE_UU_SMX: "SMX",
            Santa_Maria_Sal_Island_Cabo_Verde_SID: "SID",
            Santa_Rosa_Argentina_RSA: "RSA",
            Santa_Rosa_CA_EE_UU_STS: "STS",
            Santander_España_SDR: "SDR",
            Santiago_Chile_SCL: "SCL",
            Santiago_República_Dominicana_STI: "STI",
            Santo_Domingo_República_Dominicana_SDQ: "SDQ",
            Madrid_España_MAD: "MAD",
            New_York_EE_UU_NYC: "NYC",
        }
       
    end
    class LowFareDestination < ActiveRecord::Base
        enum destination: { 
            Aalborg_Dinamarca_ALL: "AAL", 
            Aalesund_Noruega_AES: "AES", 
            Acapulco_México_ACA: "ACA", 
            Aguascalientes_México_AGU:"AGU",
            Aguadilla_Puerto_Rico_BQN: "BQN",
            Bagotville_PQ_Canadá_YBG: "YBG",
            Bangda_China_BPX: "BPX",
            Bangkok_Tailandia_BKK: "BKK",
            Bangui_República_Centroafricana_BGF: "BGF",
            Barcelona_España_BCN: "BCN",
            Bari_Italia_BRI: "BRI",
            Barisal_Bangladesh_BZL: "BZL",
            Barranquilla_Colombia_BAQ: "BAQ",
            San_Carlos_de_Bariloche_Argentina_BRC: "BRC",
            San_Diego_CA_EE_UU_SAN: "SAN",
            San_Francisco_CA_EE_UU_SFO: "SFO",
            San_José_Costa_Rica_SJO: "SJO",
            San_José_CA_EE_UU_SJC: "SJC",
            San_Juan_Puerto_Rico_SJU: "SJU",
            San_Luis_Potosi_México_SLP: "SLP",
            San_Salvador_El_Salvador_SAL: "SAL",
            Santa_Cruz_España_SPC: "SPC",
            Santa_Cruz_de_Tenerife_Canary_Islands_TFN: "TFN",
            Santa_Fe_Nuevo_México_EE_UU_SAF: "SAF",
            Santa_Maria_CA_EE_UU_SMX: "SMX",
            Santa_Maria_Sal_Island_Cabo_Verde_SID: "SID",
            Santa_Rosa_Argentina_RSA: "RSA",
            Santa_Rosa_CA_EE_UU_STS: "STS",
            Santander_España_SDR: "SDR",
            Santiago_Chile_SCL: "SCL",
            Santiago_República_Dominicana_STI: "STI",
            Santo_Domingo_República_Dominicana_SDQ: "SDQ",
            Madrid_España_MAD: "MAD",
            New_York_EE_UU_NYC: "NYC",
        }
       
    end
end

app/views/home/_carousel.html.erb
<aside id="colorlib-hero">
    <div class="flexslider">
        <ul class="slides">
            <li style="background-image: url(/assets/img_bg_1.jpg);">
                <div class="overlay"></div>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12 slider-text">
                            <div class="slider-text-inner text-center">
                                <h2>2 Days Tour</h2>
                                <h1>Amazing Maldives Tour</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li style="background-image: url(/assets/img_bg_2.jpg);">
                <div class="overlay"></div>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12 slider-text">
                            <div class="slider-text-inner text-center">
                                <h2>10 Days Cruises</h2>
                                <h1>From Greece to Spain</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li style="background-image: url(/assets/img_bg_5.jpg);">
                <div class="overlay"></div>
                <div class="container-fluids">
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12 slider-text">
                            <div class="slider-text-inner text-center">
                                <h2>Explore our most tavel agency</h2>
                                <h1>Our Travel Agency</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li style="background-image: url(/assets/img_bg_4.jpg);">
                <div class="overlay"></div>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12 slider-text">
                            <div class="slider-text-inner text-center">
                                <h2>Experience the</h2>
                                <h1>Best Trip Ever</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </li>	   	
            </ul>
        </div>
</aside>

app/views/home/_footer.html.erb
<footer id="colorlib-footer" role="contentinfo">
    <div class="container">
        <div class="row row-pb-md">
            <div class="col-md-3 colorlib-widget">
                <h4>Tour Agency</h4>
                <p>Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit. Eos cumque dicta adipisci architecto culpa amet.</p>
                <p>
                    <ul class="colorlib-social-icons">
                        <li><a href="#"><i class="icon-twitter"></i></a></li>
                        <li><a href="#"><i class="icon-facebook"></i></a></li>
                        <li><a href="#"><i class="icon-linkedin"></i></a></li>
                        <li><a href="#"><i class="icon-dribbble"></i></a></li>
                    </ul>
                </p>
            </div>
            <div class="col-md-2 colorlib-widget">
                <h4>Book Now</h4>
                <p>
                    <ul class="colorlib-footer-links">
                        <li><a href="#">Flight</a></li>
                        <li><a href="#">Hotels</a></li>
                        <li><a href="#">Tour</a></li>
                        <li><a href="#">Car Rent</a></li>
                        <li><a href="#">Beach &amp; Resorts</a></li>
                        <li><a href="#">Cruises</a></li>
                    </ul>
                </p>
            </div>
            <div class="col-md-2 colorlib-widget">
                <h4>Top Deals</h4>
                <p>
                    <ul class="colorlib-footer-links">
                        <li><a href="#">Edina Hotel</a></li>
                        <li><a href="#">Quality Suites</a></li>
                        <li><a href="#">The Hotel Zephyr</a></li>
                        <li><a href="#">Da Vinci Villa</a></li>
                        <li><a href="#">Hotel Epikk</a></li>
                    </ul>
                </p>
            </div>
            <div class="col-md-2">
                <h4>Blog Post</h4>
                <ul class="colorlib-footer-links">
                    <li><a href="#">The Ultimate Packing List For Female Travelers</a></li>
                    <li><a href="#">How These 5 People Found The Path to Their Dream Trip</a></li>
                    <li><a href="#">A Definitive Guide to the Best Dining and Drinking Venues in the City</a></li>
                </ul>
            </div>

            <div class="col-md-3 col-md-push-1">
                <h4>Contact Information</h4>
                <ul class="colorlib-footer-links">
                    <li>291 South 21th Street, <br> Suite 721 New York NY 10016</li>
                    <li><a href="tel://1234567920">+ 1235 2355 98</a></li>
                    <li><a href="mailto:info@yoursite.com">info@yoursite.com</a></li>
                    <li><a href="#">yoursite.com</a></li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart2" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></span> 
                    <span class="block">Demo Images: <a href="http://unsplash.co/" target="_blank">Unsplash</a> , <a href="http://pexels.com/" target="_blank">Pexels.com</a></span>
                </p>
            </div>
        </div>
    </div>
</footer>

app/views/home/_navigation.html.erb
<nav class="colorlib-nav" role="navigation">
			<div class="top-menu">
				<div class="container-fluid">
					<div class="row">
						<div class="col-xs-2">
							<div id="colorlib-logo"><a href="index.html">Travelwise</a></div>
						</div>
						<div class="col-xs-10 text-right menu-1">
							<ul>
								<li class="active"><a href="index.html">Home</a></li>
								<li class="has-dropdown">
									<a href="tours.html">Travelwise</a>
									<ul class="dropdown">
										<li><a href="#">Destination</a></li>
										<li><a href="#">Cruises</a></li>
										<li><%= link_to "Hotels", hotel_index_path%></li>
										<li><%= link_to "Airline Info", flight_index_path%></li>
									</ul>
								</li>
								<li><%= link_to "Hotels", hotel_index_path%></li>
								<li><%= link_to "Airline Info", flight_index_path%></li>
								<li><%= link_to("Countries", travel_index_path) %></li>								</li>
								<li><a href="about.html">About</a></li>
								<%if current_user%>

									<li>
									<%= link_to("logout", destroy_user_session_path, method: :delete) %>
									</li>
								<%else%>
									<li><%= link_to "Sign Up", new_user_registration_path%></li>
									<li><%= link_to "Log in", new_user_session_path%></li>
								<%end%>

							</ul>
						</div>
					</div>
				</div>
			</div>
		</nav>