config/routes.rb
Rails.application.routes.draw do
  get 'hotel/index'
  get 'travel/index'
  get 'home/index'
  get 'flight/index'

  devise_for :users
  root to: "home#index"
  
  get '/search' => 'travel#search'
  get '/searchhotel' => 'hotel#searchhotel'
  get '/airline_info' => 'flight#airline_info'
  get '/flight_inspiration' => 'flight#flight_inspiration'
  get '/flight_lowfare' => 'flight#flight_lowfare'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/flight_controller.rb
require 'amadeus'
require "json"

class FlightController < ApplicationController
  def index
  end

  def airline_info
    if(params[:airlinecode].blank?)
      flash[:alert] = 'Could not get Airline Info'
    else
      airline = find_airline_info_bycode(params[:airlinecode])
      unless airline
        flash[:alert] = 'Could not get Airline Info'
        return render action: :index
      end
      
    end

    @Airline = airline
  end

  def flight_inspiration

    if(params[:citycode].blank?)
      flash[:alert] = 'Could not get Flight Info'
    else
      flight_inspiration = find_flight_inspiration_bycode(params[:citycode])
      unless flight_inspiration
        flash[:alert] = 'Could not get Flight Info'
        return render action: :index
      end
      
    end

    @FlightInsp = flight_inspiration
  end

  def flight_lowfare

      flight_lowfare = find_flight_lowfare(params[:origin], params[:destination], params[:departuredate], params[:arrivaldate])

      unless flight_lowfare
        flash[:alert] = 'Could not get Flight Low fare Info'
        return render action: :index
      end
      @flightSegments = flight_lowfare
    end

  def find_flight_lowfare(origin, destination, departuredate, arrivaldate)
    amadeus = flight_conexion()
    response = amadeus.shopping.flight_offers.get(origin: (URI.encode(origin)), destination: (URI.encode(destination)), departureDate: (URI.encode(departuredate)), returnDate: (URI.encode(departuredate)))
    response.result
  end

  def find_flight_inspiration_bycode(citycode)
    amadeus = flight_conexion()
    response = amadeus.shopping.flight_destinations.get(origin: (URI.encode(citycode)))

    response.data
  end

  def find_airline_info_bycode(airlinecode)
    amadeus = flight_conexion()
    response = amadeus.reference_data.airlines.get(airlineCodes: (URI.encode(airlinecode)))
    response.data
  end

  def flight_conexion()

    amadeus = Amadeus::Client.new({
      client_id: 'GfCm2MQJMp5cWOuEF3Gs1dong3lL7wrK',
      client_secret: '1a4VItWsGjz0dVIp'
    })

  end
end

app/views/flight/airline_info.html.erb
<h1>Airline Info!</h1>

<div class="container">
  <div class="row mt-5">
    <div class="col-lg-6">
      <h4>Airline info</h4>
      <dl>
      <%if !@Airline.nil? %>
        <% @Airline.each do |airline| %>
          <dt>Type</dt>
          <dd><%= airline['type'] %></dd>
          <dt>IATA Code</dt>
          <dd><%= airline['iataCode'] %></dd>
          <dt>Bussiness Name</dt>
          <dd><%= airline['businessName'] %></dd>
          <dt>Common Name</dt>
          <dd><%= airline['commonName'] %></dd>
        <%end%>
        <%end%>
      </dl>
    </div>
  </div>
</div>

app/views/flight/flight_inspiration.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-12 mt-5">
            <div class="mx-auto mt5" style="width: 900px">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th>Type </th>
                    <th>Origin</th>
                    <th>Destination</th>
                    <th>Departure Date</th>
                    <th>Return Date</th>
                    <th>Price</th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                    <th>Type </th>
                    <th>Origin</th>
                    <th>Destination</th>
                    <th>Departure Date</th>
                    <th>Return Date</th>
                    <th>Price</th>
                </tr>
                </tfoot>
                <tbody>
                <% @FlightInsp.each do |flight| %>
                <tr>
                    <td><%= flight['type']%></td>
                    <td><%= flight['origin']%></td>
                    <td><%= flight['destination']%></td>
                    <td><%= flight['departureDate']%></td>
                    <td><%= flight['returnDate']%></td>
                    <td><%= flight['price']['total']%></td>
                </tr>
                <% end %>
            </tbody>
            </table>
            </div>
        </div>
    </div>
</div>

app/views/flight/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 mt-5">
      <div class="mx-auto mt-5" style="width: 400px">
        <%= form_with(url: airline_info_path, method: 'get', local: true) do %>
          <div class="form-group">
                  
          <%= label_tag :airlinecode, 'Search for a airline information by code '%>
            <%= text_field_tag :airlinecode, nil, placeholder: 'Eg. AA', class: 'form-control' %>
          </div>
          <%= button_tag 'Search', class: 'btn btn-success btn-block' %>
        <% end %>
      </div>
      <div class="mx-auto mt-5" style="width: 400px">
        <%= form_with(url: flight_inspiration_path, method: 'get', local: true) do %>
          <div class="form-group">
            <%= label_tag :citycode, 'Search for flights offers by code '%>
            <%= text_field_tag :citycode, nil, placeholder: 'Eg. LON', class: 'form-control' %>
          </div>
          <%= button_tag 'Search', class: 'btn btn-success btn-block' %>
        <% end %>
      </div>
      <div class="col-lg-12 mt-5">
      <% if flash[:alert] %>
        <div class="alert alert-warning"><%= flash[:alert] %></div>
      <% end %>

      <div class="mx-auto mt-5" style="width: 400px">
    </div>
  </div>
</div>